### ISSUE TITLE
release branch not building on travis

### ISSUE THREAD

**Issue by gerritvanos** [R2D2-2019/sound#4]
i noticed a PR was merged today, the PR did build but it was 14 days ago, in the mean time the .travis.yml file and the build repo were heavily changed. I advise you to update the travis.yml with the file from the template-arduino folder. (after you updated your R2D2-build repo)

**Comment by YouriMulder** [comment]
Created a pull request to test the new travis file.
https://github.com/R2D2-2019/sound/pull/5

**Comment by gerritvanos** [comment]
this already has been fixed will close it now
